---
- name: user
  hosts: demo
  any_errors_fatal: true
  tasks:
    - name: Preconfig block
      block:
        - name: Create user
          vars:
            user: sarcasm1
          user:
            name: "{{ user }}" #variables
            state: present #present-create_user/absent-deleteUser
          register: error
        - name: Install curl
          apt:
            name: curl
            update-cache: yes
          register: error
      become: true
      when: ansible_facts['distribution'] == 'Cent'
      rescue:  # catch error handler
        - name: Some error print
          debug:
            var: error
      always: # finally
        - name: Reboot
          debug:
            msg: "Reboooooting"
      #ansible-playbook -i hosts.ini user.yml -K  (-K - give opportunities to enter "become_password")

